Update update_readme.yml

diff --git a/.github/workflows/update_readme.yml b/.github/workflows/update_readme.yml
--- a/.github/workflows/update_readme.yml
+++ b/.github/workflows/update_readme.yml
@@ -35,12 +35,11 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip || echo "Failed to upgrade pip"
-
         if [ -f "requirements.txt" ]; then
-          pip install -r requirements.txt || echo "Failed to install dependencies"
+          pip install --no-cache-dir --progress-bar off --upgrade -r requirements.txt || echo "Failed to install dependencies"
         else
           echo "requirements.txt not found, installing default dependencies"
-          pip install requests pandas || echo "Failed to install default dependencies"
+          pip install --no-cache-dir --progress-bar off requests pandas || echo "Failed to install default dependencies"
         fi
 
     - name: Run update.py script
